ALTER TABLE [File] NOCHECK CONSTRAINT all
ALTER TABLE [inquiry] NOCHECK CONSTRAINT all
ALTER TABLE [inquiryworkscope] NOCHECK CONSTRAINT all
ALTER TABLE [Measurement] NOCHECK CONSTRAINT all
ALTER TABLE [Design] NOCHECK CONSTRAINT all
ALTER TABLE [Quotation] NOCHECK CONSTRAINT all
DELETE FROM [File]
DELETE FROM [inquiry]
DELETE FROM [inquiryworkscope]
DELETE FROM [Measurement]
DELETE FROM [Design]
DELETE FROM [Quotation]
ALTER TABLE [File] CHECK CONSTRAINT all
ALTER TABLE [inquiry] CHECK CONSTRAINT all
ALTER TABLE [inquiryworkscope] CHECK CONSTRAINT all
ALTER TABLE [Measurement] CHECK CONSTRAINT all
ALTER TABLE [Design] CHECK CONSTRAINT all
ALTER TABLE [Quotation] NOCHECK CONSTRAINT all