CREATE TABLE [dbo].[InquiryWorkscope] (
    [InquiryWorkscopeId]      INT            IDENTITY (1, 1) NOT NULL,
    [InquiryId]               INT            NULL,
    [WorkscopeId]             INT            NULL,
    [IsMeasurementDrawing]    BIT            NULL,
    [MeasurementAssignedTo]   INT            NULL,
    [DesignAssignedTo]        INT            NULL,
    [InquiryStatusId]         INT            NULL,
    [MeasurementScheduleDate] NVARCHAR (50)  NULL,
    [DesignScheduleDate]      NVARCHAR (50)  NULL,
    [IsDesignApproved]        BIT            NULL,
    [Comments]                NVARCHAR (MAX) NULL,
    [IsActive]                BIT            NULL,
    [IsDeleted]               BIT            NULL,
    [CreatedBy]               INT            NULL,
    [CreatedDate]             NVARCHAR (50)  NULL,
    [UpdatedBy]               INT            NULL,
    [UpdatedDate]             NVARCHAR (50)  NULL,
    CONSTRAINT [PK_InquiryMeasurement] PRIMARY KEY CLUSTERED ([InquiryWorkscopeId] ASC),
    CONSTRAINT [FK_InquiryMeasurement_Inquiry] FOREIGN KEY ([InquiryId]) REFERENCES [dbo].[Inquiry] ([InquiryId]),
    CONSTRAINT [FK_InquiryMeasurement_WorkScope] FOREIGN KEY ([WorkscopeId]) REFERENCES [dbo].[WorkScope] ([WorkScopeId]),
    CONSTRAINT [FK_InquiryWorkscope_InquiryStatus] FOREIGN KEY ([InquiryStatusId]) REFERENCES [dbo].[InquiryStatus] ([InquiryStatusId]),
    CONSTRAINT [FK_InquiryWorkscope_User] FOREIGN KEY ([MeasurementAssignedTo]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_InquiryWorkscope_User1] FOREIGN KEY ([DesignAssignedTo]) REFERENCES [dbo].[User] ([UserId])
);

