CREATE TABLE [dbo].[Inquiry] (
    [InquiryId]             INT             IDENTITY (1, 1) NOT NULL,
    [InquiryCode]           NVARCHAR (4000) NULL,
    [InquiryName]           NVARCHAR (500)  NULL,
    [InquiryDescription]    NVARCHAR (500)  NULL,
    [InquiryStartDate]      NVARCHAR (50)   NULL,
    [InquiryDueDate]        NVARCHAR (50)   NULL,
    [InquiryEndDate]        NVARCHAR (50)   NULL,
    [CustomerId]            INT             NULL,
    [BranchId]              INT             NULL,
    [BuildingId]            INT             NULL,
    [IsEscalationRequested] BIT             NULL,
    [AddedBy]               INT             NULL,
    [IsActive]              BIT             NULL,
    [IsDeleted]             BIT             NULL,
    [CreatedBy]             INT             NULL,
    [CreatedDate]           NVARCHAR (50)   NULL,
    [UpdatedBy]             INT             NULL,
    [UpdatedDate]           NVARCHAR (50)   NULL,
    CONSTRAINT [PK_Inquiry] PRIMARY KEY CLUSTERED ([InquiryId] ASC),
    CONSTRAINT [FK_Inquiry_Branch] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[Branch] ([BranchId]),
    CONSTRAINT [FK_Inquiry_bUILDING] FOREIGN KEY ([BuildingId]) REFERENCES [dbo].[Building] ([BuildingId]),
    CONSTRAINT [FK_Inquiry_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer] ([CustomerId]),
    CONSTRAINT [FK_Inquiry_User] FOREIGN KEY ([AddedBy]) REFERENCES [dbo].[User] ([UserId])
);

