CREATE TABLE [dbo].[Measurement] (
    [MeasurementId]          INT            IDENTITY (1, 1) NOT NULL,
    [MeasurementName]        NVARCHAR (500) NULL,
    [MeasurementDescription] NVARCHAR (MAX) NULL,
    [MeasurementDetailId]    INT            NULL,
    [MeasurementStatusId]    INT            NULL,
    [MeasurementComment]     NVARCHAR (500) NULL,
    [FeesId]                 INT            NULL,
    [InquiryWorkscopeId]     INT            NULL,
    [MeasurementTakenBy]     INT            NULL,
    [KitchenDesignInfoId]    INT            NULL,
    [WardrobeDesignInfoId]   INT            NULL,
    [IsMeasurementApproved]  BIT            NULL,
    [MeasurementApprovedBy]  INT            NULL,
    [MeasurementApprovedOn]  NVARCHAR (50)  NULL,
    [IsActive]               BIT            NULL,
    [IsDeleted]              BIT            NULL,
    [CreatedBy]              INT            NULL,
    [CreatedDate]            NVARCHAR (50)  NULL,
    [UpdatedBy]              INT            NULL,
    [UpdatedDate]            NVARCHAR (50)  NULL,
    CONSTRAINT [PK_Measurement] PRIMARY KEY CLUSTERED ([MeasurementId] ASC),
    CONSTRAINT [FK_Measurement_Fees] FOREIGN KEY ([FeesId]) REFERENCES [dbo].[Fees] ([FeesId]),
    CONSTRAINT [FK_Measurement_InquiryWorkscope] FOREIGN KEY ([InquiryWorkscopeId]) REFERENCES [dbo].[InquiryWorkscope] ([InquiryWorkscopeId]),
    CONSTRAINT [FK_Measurement_KitchenDesignInfo] FOREIGN KEY ([KitchenDesignInfoId]) REFERENCES [dbo].[KitchenDesignInfo] ([KDIId]),
    CONSTRAINT [FK_Measurement_MeasurementDetail] FOREIGN KEY ([MeasurementDetailId]) REFERENCES [dbo].[MeasurementDetail] ([MeasurementDetailId]),
    CONSTRAINT [FK_Measurement_User] FOREIGN KEY ([MeasurementTakenBy]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_Measurement_User1] FOREIGN KEY ([MeasurementApprovedBy]) REFERENCES [dbo].[User] ([UserId]),
    CONSTRAINT [FK_Measurement_WardrobeDesignInformation] FOREIGN KEY ([WardrobeDesignInfoId]) REFERENCES [dbo].[WardrobeDesignInformation] ([WDIId])
);

